server:
  port: 82
spring:
  application:
    name: cloud-customer-service
  cloud:
    consul:
      host: 192.168.1.103
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true