server:
  port: 9527
spring:
  application:
    name: cloud-gateway  #如何在8001外面套一层9527网关？
                        #如下配置
                        #要访问8001的/payment/get/**的话要http://localhost:9527/payment/get/1
                        #淡化真实端口
                        #需要移除springboot starter web依赖
  cloud:
    gateway:
      discovery:
        locator:  #动态创建路由
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:   #多个路由  太多了怎么办？用config配置
        - id: payment_routh1  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #注册中心的微服务名
          predicates:
            - Path=/payment/get/**  # 断言，路径相匹配的进行路由
            - Host=localhost:**
        - id: payment_routh2  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          #  uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates: #断言
            - Path=/payment/lb/**  # 断言，路径相匹配的进行路由
            - After=2020-12-18T11:03:25.114+08:00[Asia/Shanghai] #在这时间之后 404 NOT_FOUND
            #- Cookie=username,zzyy
          #filters:
          #  - ...
# 注册进 eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true