server:
  port: 8006
spring:
  application:
    name: consul-provider-service
  cloud:
    consul:
      host: 192.168.1.103
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true   #健康状态失败，配置后红叉小时
